### ISSUE TITLE
TdnnComponent exception - fa and pt ASRs

### ISSUE THREAD

**Issue by Langtonm** [summa-platform/summa-asr#3]
I am trying to build/use the summa Farsi asr, I seem to get a "Unknown component type TdnnComponent" exception when I try to run it.

I have attempted to use both the pre-built engine "make asr-engine-fa" and I have also attempted to re-build the engine "make builder && make engine && make asr-engine-fa" yet I always get the same result when I try the ASR out using : -

`docker run --rm -t -v /tmp/test_media/test.wav:/test.wav summaplatform/asr-fa:latest ./transcribe.py /model /test.wav`

I've tested the other languages and I am able to build and run the de, es, lv, ru, uk ASRs successfully however both the fa, pt ASRs immediately fail due to the TdnnComponent exception e.g. :-
```
LOG ([5.4.128~369-08b47]:LoadIvector():src/decoder_config.cc:134) Loading IVector extraction info.
LOG ([5.4.128~369-08b47]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG ([5.4.128~369-08b47]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
ERROR ([5.4.128~369-08b47]:ReadNew():nnet-component-itf.cc:86) Unknown component type TdnnComponent


[ Stack-Trace: ]

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::nnet3::Component::ReadNew(std::istream&, bool)
kaldi::nnet3::Nnet::Read(std::istream&, bool)
kaldi::nnet3::AmNnetSimple::Read(std::istream&, bool)
alex_asr::Decoder::LoadDecoder()
alex_asr::Decoder::Decoder(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)

python3() [0x57f58c]
.
.
.
PyEval_EvalFrameEx
python3() [0x53fc97]
PyEval_EvalCode
python3() [0x60cb42]
PyRun_FileExFlags
PyRun_SimpleFileExFlags
Py_Main
main
__libc_start_main
_start

Traceback (most recent call last):
  File "./transcribe.py", line 47, in <module>
    asr = create_asr(model)
  File "/opt/app/asr.py", line 53, in create_asr
    recogniser = Decoder(model)
  File "alex_asr/decoder.pyx", line 57, in alex_asr.decoder.Decoder.__init__ (alex_asr/decoder.cpp:979)
RuntimeError
```

**Comment by Langtonm** [comment]
I had to add "sox" into the list of packages to be installed before I could get the Docker file working : -
RUN apt-get update -qq && apt-get install -y \
    git bzip2 wget \
    g++ make python python3 python3-pip \
    zlib1g-dev automake autoconf libtool subversion \
    libatlas-base-dev sox && pip3 install --upgrade pip
